import sys

from textblob import TextBlob
from textblob.classifiers import NaiveBayesClassifier

reload(sys)
sys.setdefaultencoding("utf-8")


train = [('Can you change watch bands', 'customization'),
('Sorry that the 1.45 doesnt have a speaker. Hope the 1.63 wont overpower my smallish wrist! How is the sound quality and how easy to adjust?', 'sound'),
('why are you selling the google g watch at $294 when it is $229 everywhere else?', 'price'),
('Sorry that the 1.45 doesnt have a speaker. Hope the 1.63 wont overpower my smallish wrist! How is the sound quality and how easy to adjust?', 'sound'),
('Does this come with a charging dock?', 'accessories'),
('Can you change watch bands', 'customization'),
('How to choose M or S', 'customization'),
('Can you take answer a call without having to take out your phone?', 'calls'),
('the charger is included?', 'accessories'),
('is a screen protector necessary?', 'accessories'),
('is a screen protector necessary?', 'accessories'),
('can you respond to test messages with this watch', 'features'),
('is it waterproof?', 'waterproof'),
('Will this watch work efficiently with iphone 6 plus and ios 9 ?, please clarify.', 'hardware'),
('Can the battery last for a marathon 4 hour run with bluetooth headphones?', 'battery'),
('Does it track sleep?', 'features'),
('Can you answer calls and talk and listen with this watch?', 'features'),
('I heard that this can only pair with low-power bluetooth devices. How limiting is this?', 'hardware'),
('Can the battery last for a marathon 4 hour run with bluetooth headphones?', 'battery'),
('Does it track sleep?', 'features'),
('Is it difficult to see the screen outside?', 'hardware'),
('does it answer or make calls?', 'features'),
('can the band be replaced on this new Samsung Gear Fit 2', 'customization'),
('Why is this listed as a women watch? Girly?', 'customization'),
('Can the band be changed? Also can multiple alarms be set?', 'features'),
('Are the straps interchangeable? If I bought brown and got tired of it, can I swap another coler instead?', 'customization'),
('So i have a few questions can i use while washing my hands/dishes? and hows the battery? is the screen bright? and is the speaker loud(I work out side', 'features'),
('Can you put music on it and listen to it with Bluetooth without the phone being around', 'features'),
('Are the straps interchangeable? If I bought brown and got tired of it, can I swap another coler instead?', 'customization'),
('So i have a few questions can i use while washing my hands/dishes? and hows the battery? is the screen bright? and is the speaker loud(I work out side', 'features'),
('Can i make a phone call or receive a phone call from the watch? it is a feature that gear neo has and i would like to keep.', 'features'),
('Does it work with the galaxy s4??', 'compatibility'),
('do we get a charger /usb connector with the pebble white or do i have to buy it separately ?', 'hardware'),
('Do you have to carry your smartphone with you for the watch to function', 'features'),
('Does this MOTO 360 have its own WIFI or does it need to be tethered to my phone to check email, browse internet?', 'hardware'),
('What is the sizing for large vs. small?', 'customization'),
('does it have a heart rate monitor?', 'features'),
('Does it have a constant heartrate?', 'features'),
('work with iphone?', 'compatibility'),
('Do you need your phone nearby in order for the watch to work?', 'hardware'),
('Does it work with Samsung Galaxy S5?', 'compatibility'),
('Will it show who is calling? instead of digging your phone out of your pocket to see.', 'features'),
('I use my BT headset to listen to podcasts constantly on my phone. Will the fact that this works via BT also interfere?', 'hardware'),
('Does it come with a charger?', 'hardware'),
('Its water resistant?', 'hardware'),
('Water resistant?', 'hardware'),
('Does it have wifi/can you use the web on it?', 'hardware'),
('can anyone tell me if the heart rate monitor is accurate?', 'features'),
('does the conituous heart rate monitor upload a graph or something? Can the heart rate monitor and stop watch be on at the same time?', 'features'),
('Is the dial face active all the time (i.e. does it switch off with inactivity)? Is the dial lighted for night view? Can brightness be manually cont', 'features'),
('Does it have a constant heartrate?', 'features'),
('Does the pebble smart watch have heart rate capability?', 'features'),
('What is the difference between the $99 dollar watch and the $199 dollar watch and is it worth the difference?', 'price'),
('How is it connected to the Web?', 'features'),
('Does whatsapp notificationbs appear on it?', 'features'),
('what is the Pebble Smartwatch Steel compared to the Pebble Smartwatch', 'hardware'),
('When I go for a run, would I still need to have my phone with me for the watch to record distance and pace?', 'hardware'),
('Only one phone can be Bluetooth paired with my cars for phone answering purposes. Can my S4 be paired with the watch and with my car to answer phone?', 'hardware'),
('Is it compatible with the Iphone 5s or 6? iOS8?', 'compatibility'),
('can you make or answer calls?', 'features'),
('does this watch work with the LG Optimus Dynamic II', 'compatibility'),
('Is the watch water resistant at all?', 'hardware'),
('Does the watch continue to track your steps if you dont carry your phone during a workout?', 'features'),
('Can I play music from the watch?', 'features'),
('ref the sale dicription as motorola moto 360 - champagne gold metal,( 23mm) , smart watch -? what does the 23mm refering to ive seen a 18mm obtion ??', 'hardware'),
('What are its primary improvements over the GearFit?', 'features'),
('Are the calories burned while exercising accurate?', 'features'),
('Could I use the Couch to 5k app on it?', 'features'),
('Is it accurate while pushing a syroller or shopping cart?', 'features'),
('How is the battery with GPS active?', 'battery'),
('Does this watch have a mic and speaker so I could talk on it?', 'features'),
('What size range does the band fit?', 'customization'),
('how long will the battery last with gps on and heat rate tracking on compared to off?', 'battery'),
('Does it tell me my running pace in real time?', 'features'),
('Does it record heart rate while you work out and constant or do you need to be standing still. also is this work with my Samsung s Health app?', 'features'),
('can i use the watch with spotify without having my phone with me?', 'features'),
('Battery life is enough for 2 hr workout session hearing music?', 'battery'),
('Is the 1st Gen charger compatible with this 2nd Gen watch?', 'compatibility'),
('Can you set a pace alert (notify when you go above or below a set pace)', 'features'),
('Does the hr monitor works as well and registers data if i decide to use different running apps such as nike+ or runkeeper?', 'features'),
('Can you change the background image or screen to whatever you want?', 'features'),
('can you receive and answer emails and text messages?', 'features'),
('does it have camera?', 'features'),
('Does it have keyboard', 'features'),
('Is the watch water resistant?', 'hardware'),
('Can you run Sleep as Android or other sleep tracking apps with this smart watch?', 'features'),
('How many daily alarms can you set up on this watch?', 'features'),
('What is the average time you get on a charge?', 'battery'),
('can you answer calls with this watch ?', 'features'),
('does it have a heart rate monitor?', 'features'),
('Can I take it swimming', 'hardware'),
('is this water resistant?', 'hardware'),
('Does it vibrate', 'hardware'),
('Will this work on iPhone', 'compatibility'),
('Does it work for iPhone', 'compatibility'),
('Can you change the background image or screen to whatever you want?', 'features'),
('can you receive and answer emails and text messages?', 'features'),
('does it have camera?', 'features'),
('Does it have keyboard', 'features'),
('Does this work with the iPhone 6/6s?', 'compatibility'),
('Does anyone else have the issue of this watch not charging past 82%? i have to remove it off charger and charge again.', 'battery'),
('Will this work with the Samsung S7 Edge?', 'compatibility'),
('Does the front face metal cover replaceable with different colors?', 'customization'),
('can u text and call on this', 'features'),
('Is it water proof and does it crash when connected to the Apple iOS 9.2.1 ? have a pebble steel that crashes everyday!!', 'hardware'),
('Can i see the same emails that i can view on my phone? if so, can i scroll down through the email, and also scroll down to the next email?', 'features'),
('Is it worth buying if you have an iPhone?', 'features'),
('Can i use it with the galaxy s6 edge?', 'compatibility'),
('Can this watch make and receive calls?', 'features'),
('Does this watch answer phone calls and play music? Also does it have a headphone slot?', 'features'),
('Is this watch version 2 or version 1?', 'hardware'),
('Is it the chrome one? In stock and Ready to ship?', 'hardware'),
('can i install whatsapp in this watch ?', 'features'),
('is this phone compatible with the samsung 6', 'compatibility'),
('Is this generation 1 or generation 2?', 'hardware'),
('Does the heart rate monitor works when arm is moving (like running?) with latest firmware?', 'features'),
('Can i get rid of the horizontal bottom line?', 'hardware'),
('Does this watch have a mic and speaker so I could talk on it?', 'hardware'),
('What size range does the band fit?', 'customization'),
('how long will the battery last with gps on and heat rate tracking on compared to off?', 'battery'),
('Does it tell me my running pace in real time?', 'features'),
('Does it record heart rate while you work out and constant or do you need to be standing still. also is this work with my Samsung s Health app?', 'features'),
('can i use the watch with spotify without having my phone with me?', 'features'),
('Battery life is enough for 2 hr workout session hearing music?', 'battery'),
('Is the 1st Gen charger compatible with this 2nd Gen watch?', 'battery'),
('Can you set a pace alert (notify when you go above or below a set pace)', 'features'),
('Does the hr monitor works as well and registers data if i decide to use different running apps such as nike+ or runkeeper?', 'features'),
('Does this watch still kinda hold up today?', 'hardware'),
('can you answer and make calls from this', 'features'),
('can you connect it to bluethooth headphones and listen to music?', 'hardware'),
('is it touchscreen', 'hardware'),
('Does clock have vibrating alarm?', 'features'),
('Can you connect to both the Pebble and your cars Bluetooth Stereo (mainly for hands free phone calls) at the same time using an Android 4.2 phone?', 'compatibility'),
('Does it eat up many gb of data on your plan? i had it on for 2 weeks and i used up all my 6 gb.', 'price'),
('Does the vibrating alarm work well enough to wake you?', 'features'),
('Does the caller ID show the contact information stored on your iPhone? Just the phone number? Or the publicly listed caller ID info if avail?', 'features'),
('Is this watch compatible with a HTC ONE M8?', 'compatibility'),
('Would you recommend this against the potential iwatch if it does indeed exist?', 'hardware'),
('Is the Pebble watch compatible with the Polar H7 Bluetooth Smart Heart Rate Sensor strap?', 'compatibility'),
('iphone 4', 'compatibility'),
('Will it let you know when you have an imessage?', 'features'),
('is the watch operative as a blue tooth phone', 'features'),
('Does the charger come with it?', 'hardware'),
('will it work with an iphone 3?', 'compatibility'),
('Is it compatible with Android Icecream sandwich?', 'compatibility'),
('Does it support the Arabic language in menus or at least support reading messages and emails in Arabic?', 'compatibility'),
('Does it works with Blackberry?', 'compatibility'),
('It Is waterproof??', 'waterproof'),
('is the watch compatible with ios 8?', 'compatibility'),
('Sync or Works with iphone?', 'compatibility'),
('How durable is the watch band for the moto sport?','hardware'),
('is it waterproof', 'waterproof'),
('its compatible with Android 6.0.1 marshmallow?', 'compatibility'),
('what color should I get?', 'customization'),
('does it work with', 'compatibility'),
('Does it work with lg g5?', 'compatibility'),
('What\'s in the box when you get it?', 'hardware'),
('Does it work with the LG Lucid?', 'compatibility'),
('Does the black LG dislay in color?', 'hardware'),
('Does it work with blu 6.0 hd?', 'compatibility'),
('Does it work with windows phone?', 'compatibility'),
('is it waterproof?', 'waterproof'),
('Do you have to have a phone to use this?', 'hardware'),
('I\'m using iPhone 5', 'compatibility'),
('works with windows phones?', 'compatibility'),
('can it work with windows phone?', 'compatibility'),
('Is the wrist strap adjustable?', 'customization'),
('bands changeable', 'customization'),
('Is there a mode to keep the display on?', 'hardware'),
('Is there an app for the i phone 5s?', 'compatibility'),
('Is it water resistant at all?', 'waterproof'),
("Does it come with a charging dock?","hardware"),
("Is it avaliable in black metal?","hardware"),
("Will it run on iOS?","compatibility"),
("Will this work with my Apple air pad or my Samson phone?","compatibility")

]

cl = NaiveBayesClassifier(train)
# print cl.classify("will it work under water?")

f = open ("corpus_smartwatch.txt", "r")
text = f.read()
blob = TextBlob(text, classifier=cl)

for s in blob.sentences:
    print "\""+s.string+"\","+s.classify()